feat: number and epoch types, IntervalValue list parsing
poliastro/czml3 pull request #151
Opened 2024-07-16 17:46 UTC by vishwa2710

2024-07-16 18:44 UTC, Stoops-ML requested changes
Great work!

2024-07-16 18:44 UTC, Stoops-ML commented on src/czml3/types.py
> +        if hasattr(self._value, "to_json"):
Replace with `if isinstance(self._value, BaseCZMLObject)`

2024-07-16 22:56 UTC, vishwa2710 commented on src/czml3/types.py
> +        if hasattr(self._value, "to_json"):
```suggestion
        if isinstance(self._value, BaseCZMLObject)
```

2024-07-16 22:56 UTC, vishwa2710 commented
@Stoops-ML done!

2024-07-17 06:31 UTC, Stoops-ML reviewed
Small fix required.

2024-07-17 06:31 UTC, Stoops-ML commented on src/czml3/types.py
> +        if isinstance(self._value, BaseCZMLObject)
Missing colon

2024-07-17 07:52 UTC, vishwa2710 commented on src/czml3/types.py
> +        if isinstance(self._value, BaseCZMLObject)
```suggestion
        if isinstance(self._value, BaseCZMLObject):
```

2024-07-17 07:53 UTC, vishwa2710 commented
🤦 thanks! This should be good.

2024-07-17 08:17 UTC, Stoops-ML commented
The test `test_interval_value()` failed because the class you created `CustomValue` is not a subclass of `BaseCZMLObject`.

2024-07-17 08:32 UTC, vishwa2710 commented
Ah sorry for the mess. I wasn't running the tests locally as the setup is not containerized. I went through the motions and I've tested this locally. It should pass now 💯

2024-07-17 08:33 UTC, vishwa2710 commented
Would we be opposed to containerizing this repo and adding a makefile with some simple commands for testing, formatting, etc.?

2024-07-17 08:40 UTC, Stoops-ML commented
Need to run `ruff format` and `ruff check --fix` to format the code.

2024-07-17 08:41 UTC, Stoops-ML commented
> Would we be opposed to containerizing this repo and adding a makefile with some simple commands for testing, formatting, etc.?

Open an issue on this. I'd like to hear what others think about this.

2024-07-17 09:03 UTC, vishwa2710 commented
Checked with ruff 👍

2024-07-17 09:08 UTC, Stoops-ML approved these changes

2024-07-17 09:08 UTC, merged