Add polylines
poliastro/czml3 pull request #21
Opened 2019-07-20 07:18 UTC by Sedictious

2019-07-20 13:06 UTC, astrojuanlu requested changes
All looks good! However there are many parts not covered by tests (see Codecov message). Could we add more of those, especially for the new classes in `types.py`, and also `ArcType` and `ShadowMode`?

2019-07-21 07:58 UTC, Sedictious commented
@Juanlu001 I think this should be good to go 😄

2019-07-21 07:59 UTC, astrojuanlu approved these changes

2019-07-21 08:00 UTC, merged

2019-07-21 08:00 UTC, Juanlu001 commented
Merging, thanks a lot!