Added support for CZML rectangles
poliastro/czml3 pull request #58
Opened 2020-02-16 10:43 UTC by imiara

core.py - added rectangle attribute to the CZML Packet class
properties.py - added CartographicRectangle, RectangleCoordinates CZML object classes

2020-02-16 10:47 UTC, imiara commented
Hi,
I've reformatted properties.py with black and forced push, but I then I couldn't update the pull request, so I've closed it and opened this one. hope it's OK now.

2020-02-16 12:14 UTC, Juanlu001 commented
No problem @imiara! Now quality is good and nothing broke, but we should add some tests so the coverage does not decrease :) Do you feel confident to use some of the existing ones as inspiration?

2020-02-16 12:15 UTC, Juanlu001 commented on src/czml3/properties.py
> +class Cartographicrle(BaseCZMLObject, Interpolatable, Deletable):
Is this name OK?

2020-02-18 18:18 UTC, idanmiara reviewed
Hi,
I've pushed a new test.
I'm not sure the meaning of the CI output...
could you clarify please?

2020-02-18 18:18 UTC, idanmiara commented on src/czml3/properties.py
> +class Cartographicrle(BaseCZMLObject, Interpolatable, Deletable):
oops.. now fixed.

2020-02-18 18:55 UTC, Juanlu001 commented
Thanks @idanmiara , this is almost there! `isort` is complaining about the order of the imports (yes, we're _that_ picky). Just apply `$ tox -e reformat` (you need `pip install tox` first) and commit the results.

2020-02-18 21:01 UTC, astrojuanlu requested changes
It seems to me that you are reimplementing part of the `tempfile` module itself, perhaps using some private functions, and that's why MyPy is complaining. I really like the tests here, if you can find a simpler way of making the last two, we would be in a position to merge this!

2020-02-18 21:01 UTC, astrojuanlu commented on tests/test_rectangle_image.py
> +    filename = next(tempfile._get_candidate_names()) + suffix
MyPy is complaining about this function, which apparently does not exist?

2020-02-18 21:01 UTC, astrojuanlu commented on tests/test_rectangle_image.py
> +            dir_name = tempfile._get_default_tempdir()
This doesn't exist either

2020-02-18 21:05 UTC, Juanlu001 commented
For example https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile

2020-02-19 21:19 UTC, idanmiara commented
Hi,
I don't know MyPy, but these function do exist in my environment. Maybe it doesn't like that they are underscored prefixed. Anyway I did find that there is a built in function that I can use instead, so no problem. tempfile.NamedTemporaryFile creates a temp file, I just needed a temp filename - tempfile.mktemp() does that.
Could you tell me where do you find these reports or how do I run all these tests myself before pushing it? I've tried to look into the codecov report but I couldn't find what's going on there.

2020-02-20 07:56 UTC, Juanlu001 commented
Hi @idanmiara - to see these checks, you can click here:

![Screenshot_2020-02-20 Added support for CZML rectangles by idanmiara · Pull Request #58 · poliastro czml3](https://user-images.githubusercontent.com/316517/74912281-a841d600-53be-11ea-99d8-05427d48b5bd.png)

And see the details of every step.

To check if the quality step will pass you don't need mypy either, doing `tox -e quality` will run `isort`, `mypy`, `black` and `flake8`. Also, if you do `tox -e test`, all the tests will be run.

2020-02-20 07:59 UTC, astrojuanlu approved these changes
I don't want to annoy you with more reviews, for I think this is good enough. Thank you very much! :sparkles:

2020-02-20 07:59 UTC, merged

2020-02-20 08:10 UTC, idanmiara commented
@Juanlu001 Thank you very much for spending the time with this code review and for merging it!
When do you plan to make new releases and publish to PyPI and to Conda ? Do you do it regularly ?

2020-02-20 09:00 UTC, Juanlu001 commented
I made a couple of fixes: #59 and #60 (so it ended up being called `Rectangle` like the original at https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Rectangle).

For the moment I don't do releases regularly, so now that I'm at it I'll make a new one with these changes :) Stay tuned!

2020-02-20 09:05 UTC, Juanlu001 commented
czml3 0.5.3 available with `Rectangle` :tada: